### ISSUE TITLE
Cannot find database driver: org.mariadb.jdbc.Driver

### ISSUE THREAD

**Issue by de1m** [kilna/liquibase-mariadb-docker#6]
I cannot use the docker image for mariadb.
I'get the error:

```
vagrant@filercon:/nodejs/adito2019DB/db_changes$ sudo docker run --rm -e LIQUIBASE_HOST=k8s-test04.aditosoftware.local -e LIQUIBASE_USERNAME=adito -e LIQUIBASE_PASSWORD=JAlfj0923mlkjLAKLmflAjFALkmf -e LIQUIBASE_DATABASE=adito -e LIQUIBASE_PORT=30308 -e LIQUIBASE_LOGLEVEL=debug --name db -t kilna/liquibase-mariadb liquibase dropAll
Unexpected error running Liquibase: java.lang.RuntimeException: Cannot find database driver: org.mariadb.jdbc.Driver

SEVERE 2/7/19 2:48 PM: liquibase: java.lang.RuntimeException: Cannot find database driver: org.mariadb.jdbc.Driver
liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: java.lang.RuntimeException: Cannot find database driver: org.mariadb.jdbc.Driver
        at liquibase.integration.commandline.CommandLineUtils.createDatabaseObject(CommandLineUtils.java:127)
        at liquibase.integration.commandline.Main.doMigration(Main.java:958)
        at liquibase.integration.commandline.Main.run(Main.java:188)
        at liquibase.integration.commandline.Main.main(Main.java:103)
Caused by: liquibase.exception.DatabaseException: java.lang.RuntimeException: Cannot find database driver: org.mariadb.jdbc.Driver
        at liquibase.database.DatabaseFactory.openConnection(DatabaseFactory.java:247)
        at liquibase.database.DatabaseFactory.openDatabase(DatabaseFactory.java:151)
        at liquibase.integration.commandline.CommandLineUtils.createDatabaseObject(CommandLineUtils.java:85)
        ... 3 more
Caused by: java.lang.RuntimeException: Cannot find database driver: org.mariadb.jdbc.Driver
        at liquibase.database.DatabaseFactory.openConnection(DatabaseFactory.java:199)
        ... 5 more


For more information, use the --logLevel flag
```

Docker Image:
```
vagrant@filercon:/nodejs/adito2019DB/db_changes$ sudo docker images
REPOSITORY                TAG                 IMAGE ID            CREATED             SIZE
kilna/liquibase-mariadb   latest              769b83e967c3        5 weeks ago         166MB
```
Any idea?

"ls" command in container:
```
vagrant@filercon:/nodejs/adito2019DB/db_changes$ sudo docker run -e LIQUIBASE_DATABASE=adito --rm kilna/liquibase-mariadb sh -c "ls -lah /opt/jdbc"
total 8
drwxr-xr-x    1 root     root        4.0K Dec 28 18:48 .
drwxr-xr-x    1 root     root        4.0K Dec 28 18:48 ..
-rw-r--r--    1 root     root           0 Dec 28 18:48 mariadb-java-client-2.2.1.jar
lrwxrwxrwx    1 root     root          29 Dec 28 18:48 mariadb-jdbc.jar -> mariadb-java-client-2.2.1.jar
```

**Comment by myspotontheweb** [comment]
The latest versions of this image are broken because the package jdbc jar is zero bytes. The following image tags are impacted:

* kilna/liquibase-mariadb:latest
* kilna/liquibase-mariadb:2.2.1
* kilna/liquibase-mariadb:2.2.0
* kilna/liquibase-mariadb:2.1.2

# Test

```
$ for i in latest 2.2.1 2.2.0 2.1.2; do docker run --rm -it kilna/liquibase-mariadb:$i find /opt/jdbc -size 0; done
/opt/jdbc/mariadb-java-client-2.2.1.jar
/opt/jdbc/mariadb-java-client-2.2.1.jar
/opt/jdbc/mariadb-java-client-2.1.1.jar
/opt/jdbc/mariadb-java-client-2.1.1.jar
```

**Comment by c-schinzer** [comment]
Is anyone on this to fix it? I like the idea to have such image, but it should work.
Also, we are meanwhile at mariadb-java-client-2.5.1.jar.

**Comment by de1m** [comment]
I've created my own [mariadb docker image](https://hub.docker.com/r/adito/liquibase-mariadb)
